base_url = 'http://www.visual-literacy.org/periodic_table/pix/'

pics = """spectrogram.jpg
graphic-facilitation.png
table-sbu-vs-cc.png
scenario-matrix.png
on-Track.png
metro-map.gif
temple.png
story-template.png
tree_compet_full.png
cartoon-new.png
piechart-coca-cola-annual-r.png
line-chart.png
communication-diagram.png
Flightplan.png
concept-skeleton.png
Bridge-of-Negotiation.jpg
IT-Funnel.png
RICH-PICTURE.jpg
barchart.png
area_chart.png
50_chart.png
parallel-coordinates.png
PEOPLEHYPERBOLICTREE.png
risk-process.png
timeline.png
venn.png
7steps-to-better-notes-mind.png
squre-of-oppositions.png
concentric-circles-of-marke.png
argument-slide.png
swimlane-activity-diagram.png
gantt-chart.png
perspectives-diagram.png
dilemma_diagram.png
ruler.png
elearnland.png
histogram.png
scatterplot.png
sankey-diagram.png
table-lens.png
entity-relationship.png
petri-net.png
flowchart.png
cluster-chart.png
geographic-layers.png
minto_pyramid.png
cause_effect_chain.png
toulmin-diagram.png
decision-tree.png
cpm2.png
concept-fan.png
kognitive-mapping-add-innov.png
brand-iceberg.png
learning-map.jpg
tukey-box-plot.png
pwarb.jpg
data-map.png
treemaps-news.png
parc_cone_tree.png
SysDyn.png
data-flow.gif
semantic_network.png
soft-system.png
syn-map.png
force-field.png
argument-IBIS.png
process-event-chain.png
PERT.png
evocative-knowledge-map.png
vee-software-project.png
tower-debriefing.jpg
infomural-GM.png
supply-demand-curves.png
performance-charting.png
strategy-bsc-map.png
Organigramm-cintec.png
house-of-quality-hbr.png
feedback-diagram.png
failure-tree.png
magic-quadrant.png
life-cycle.png
porter-five-forces.png
scurve.png
stakeholder-diagram.png
fishbone-plan.png
roadmapping-ifm.png
edgeworth-box.png
stragroup.png
strategic-game-board.png
organigraph.png
zwicky.png
Affinity_Diagram.png
decision-discovery.png
bcg-Matrix.png
strategy-canvas.png
porter-value-chain.png
HYPE-CURVE.png
stakeholder-rating.png
TAPS.png
spray-diagram.gif
data-flow.gif""".split('\n')

import urllib2
def g(pic):
    f = open(pic, 'wb')
    f.write(urllib2.urlopen(base_url + pic).read())
    f.close()

for pic in pics:
    g(pic)